Improve quoting of string in error messages
In particular in that one:

{{{
[Score-P] src/measurement/profiling/scorep_profile_event_base.c:187: Error: Inconsistent profile. Stop profiling: Exit event for other than current region occurred at location 0: Expected exit for region non-virtual thunk to BoundComputationTheta::getLowerBound. Exited region Subproblem::computeLowerBound
}}}

Which is now:

{{{
[Score-P] src/measurement/profiling/scorep_profile_event_base.c:187: Error: Inconsistent profile. Stop profiling: Exit event for other than current region occurred at location 0: Expected exit for region 'non-virtual thunk to BoundComputationTheta::getLowerBound'. Exited region 'Subproblem::computeLowerBound'
}}}

Subversion: revision:13957