[cray] Add FLIBS for PrgEnv-cray only
On Cray, FLIBS (via AC_F77_LIBRARY_LDFLAGS) added to
libscorep_adapter_mpi_mgmt (see
7262bf5f2dfd85f06afab54e2e0f26919ff55545, see #16), if the C compiler
is clang based, cause MPI+OpenMP installchecks to fail for
PrgEnv-intel and the branch 74-ompt:
```
  SCOREP MPICCLD    /scratch/snx3000/cfeld/builder/daint/builds/622GRfUb/2/perftools/cicd/scorep/build/build-backend/../installcheck/instrumenter_checks/bin/jacobi-mpi_omp-cc_default
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/7/../../../../lib64/libbfd.a(dwarf2.o): undefined reference to symbol 'htab_find_slot'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /users/cfeld/builder/daint/opt/binutils/2.37/os-gcc/lib/libbfd-2.37.so: error adding symbols: DSO missing from command line
```

Not sure why this libbfd related problem hasn't emerged earlier. The
OMPT adapter uses addr2line, which uses libbfd. But so does the
compiler adapter.