Fixing broken distcheck. Distcheck is broken since revision:2683. Now we are at revision:2695. This is pretty bad :-(
{{{
CC libscorep_cube_writer_la-cubew_services.lo
../../build-backend/../src/measurement/cube_writer/cubew_services.c:28:35: fatal error: cubew_compat_platform.h: No such file or directory
compilation terminated.
}}}

Subversion: revision:2697