GCC plug-in: Avoid creating duplicate variable names
GCC 14 snpshots failed because duplicate symbols:

```
/tmp/cc1oYiKh.s:14002: Error: symbol `_ZZ3foovE22__scorep_region_handle' is already defined
/tmp/cc1oYiKh.s:14015: Error: symbol `_ZZ3foovE21__scorep_region_descr' is already defined
/tmp/cc1oYiKh.s:14028: Error: symbol `_ZZ3foovE22__scorep_region_handle' is already defined
/tmp/cc1oYiKh.s:14041: Error: symbol `_ZZ3foovE21__scorep_region_descr' is already defined
```

It could be observed with a Fedora GCC 14.1.1 20240507 and the Ubuntu 24.04
GCC 14.0.1 20240412 but not with the GCC 14.1 release.

Closes #375